import { Octokit } from "@octokit/rest";

import type { GeneratedFile } from "@/lib/stacks";

export async function createRepositoryWithFiles({
  files,
  projectName,
  token,
}: {
  files: GeneratedFile[];
  projectName: string;
  token: string;
}) {
  const octokit = new Octokit({ auth: token });

  const repo = await octokit.repos.createForAuthenticatedUser({
    name: projectName,
    private: false,
    auto_init: false,
    description: "Generated by AgentStack.",
  });

  const owner = repo.data.owner.login;
  const repoName = repo.data.name;

  for (const file of files) {
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo: repoName,
      path: file.path,
      message: `Add ${file.path}`,
      content: Buffer.from(file.content, "utf8").toString("base64"),
    });
  }

  return repo.data.html_url;
}

export function getHttpStatus(error: unknown) {
  if (typeof error === "object" && error && "status" in error) {
    const status = (error as { status?: unknown }).status;
    return typeof status === "number" ? status : undefined;
  }

  return undefined;
}
