import { expect, type Page, test } from "@playwright/test";

const previewFiles = [
  {
    path: "README.md",
    content: "# playwright-smoke\n\nGenerated by the mocked preview route.\n",
  },
  {
    path: "CLAUDE.md",
    content:
      "# playwright-smoke\n\n## Agent Working Rules\nUse the mocked preview output in e2e tests.\n",
  },
  {
    path: "src/app/page.tsx",
    content:
      'export default function Home() {\n  return <main>Mocked preview</main>;\n}\n',
  },
];

test.describe.configure({ mode: "serial" });

test("homepage renders", async ({ page }) => {
  await page.goto("/");

  await expect(
    page.getByRole("main", { name: "AgentStack homepage" }),
  ).toBeVisible();
  await expect(
    page.getByRole("heading", {
      name: "Start a repo that already knows how agents should work.",
    }),
  ).toBeVisible();
  await expect(
    page.getByRole("link", { name: "Generate a repo" }),
  ).toBeVisible();
});

test("project name validation is visible", async ({ page }) => {
  await page.goto("/generate");

  await expect(
    page.getByRole("heading", { name: "Generate a repo" }),
  ).toBeVisible();

  const projectName = page.getByLabel("Project name");

  await projectName.fill("bad project");

  await expect(projectName).toHaveValue("bad project");
  await expect(projectName).toHaveAttribute("aria-invalid", "true");
  await expect(
    page.getByText("Use letters, numbers, and hyphens only."),
  ).toBeVisible();

  await projectName.fill("playwright-smoke");

  await expect(projectName).toHaveValue("playwright-smoke");
  await expect(
    page.getByText("Use letters, numbers, and hyphens only."),
  ).toBeHidden();
});

test("stack selection uses accessible radio state", async ({ page }) => {
  await page.goto("/generate");

  const stackGroup = page.getByRole("radiogroup", { name: "Choose a stack" });
  const nextTailwind = stackGroup.getByRole("radio", {
    name: /A clean App Router starter/,
  });
  const supabase = stackGroup.getByRole("radio", {
    name: /Supabase client setup/,
  });

  await expect(stackGroup).toBeVisible();
  await expect(nextTailwind).toHaveAttribute("aria-checked", "false");
  await expect(supabase).toHaveAttribute("aria-checked", "false");

  await nextTailwind.focus();
  await page.keyboard.press("Space");

  await expect(nextTailwind).toHaveAttribute("aria-checked", "true");
  await expect(supabase).toHaveAttribute("aria-checked", "false");

  await supabase.click();

  await expect(nextTailwind).toHaveAttribute("aria-checked", "false");
  await expect(supabase).toHaveAttribute("aria-checked", "true");
});

test("mocked preview renders files and keeps unsigned generation disabled", async ({
  page,
}) => {
  const previewBodies: unknown[] = [];
  let generateRequests = 0;

  await page.route("**/api/preview", async (route) => {
    previewBodies.push(route.request().postDataJSON());

    await route.fulfill({
      body: JSON.stringify({
        files: previewFiles,
        previewSessionId: "playwright-preview-session",
      }),
      contentType: "application/json",
      status: 200,
    });
  });
  await page.route("**/api/generate", async (route) => {
    generateRequests += 1;

    await route.fulfill({
      body: JSON.stringify({ error: "Generate should not be called." }),
      contentType: "application/json",
      status: 500,
    });
  });

  await page.goto("/generate");
  await page.getByLabel("Project name").fill("playwright-smoke");
  await selectNextTailwindStack(page);

  await page
    .getByRole("button", { name: "Preview generated files" })
    .click();

  await expect(
    page.getByRole("button", { exact: true, name: "CLAUDE.md" }),
  ).toBeVisible();
  await expect(
    page.getByRole("button", { exact: true, name: "README.md" }),
  ).toBeVisible();
  await expect(
    page.getByRole("button", { exact: true, name: "src/app/page.tsx" }),
  ).toBeVisible();
  await expect(page.getByText("Use the mocked preview output")).toBeVisible();

  await page
    .getByRole("button", { exact: true, name: "src/app/page.tsx" })
    .click();
  await expect(
    page.getByText("return <main>Mocked preview</main>;"),
  ).toBeVisible();

  const githubCta = page.getByRole("button", {
    name: "Sign in with GitHub to continue",
  });
  await expect(githubCta).toBeVisible();
  await expect(githubCta).toContainText("Login with GitHub");

  const generateButton = page.getByRole("button", {
    name: "Sign in with GitHub before generating the repo.",
  });
  await expect(generateButton).toBeDisabled();
  await expect(generateButton).toContainText("Generate repo");

  expect(previewBodies).toEqual([
    {
      generationOptions: {
        description: "Generated by AgentStack.",
        projectBrief: "",
        visibility: "public",
      },
      projectName: "playwright-smoke",
      stack: "next-tailwind",
    },
  ]);
  expect(generateRequests).toBe(0);
});

async function selectNextTailwindStack(page: Page) {
  await page
    .getByRole("radiogroup", { name: "Choose a stack" })
    .getByRole("radio", { name: /A clean App Router starter/ })
    .click();
}
