export const REPOSITORY_DESCRIPTION_MAX_LENGTH = 160;
export const PROJECT_BRIEF_MAX_LENGTH = 800;
export const DEFAULT_REPOSITORY_VISIBILITY = "public";
export const DEFAULT_REPOSITORY_DESCRIPTION = "Generated by AgentStack.";

export type RepositoryVisibility = "public" | "private";

export type ProjectBrief = {
  content: string;
};

export type GenerationOptions = {
  visibility: RepositoryVisibility;
  description: string;
  projectBrief: ProjectBrief | null;
};

export type GenerationOptionsField =
  | "generationOptions"
  | "visibility"
  | "description"
  | "projectBrief";

export type GenerationOptionsValidationError = {
  field: GenerationOptionsField;
  message: string;
};

export type NormalizeGenerationOptionsResult =
  | {
      ok: true;
      options: GenerationOptions;
      errors: [];
    }
  | {
      ok: false;
      options: null;
      errors: GenerationOptionsValidationError[];
    };

type GenerationOptionsInput = {
  visibility?: unknown;
  repositoryVisibility?: unknown;
  description?: unknown;
  repositoryDescription?: unknown;
  projectBrief?: unknown;
};

export function validateRepositoryVisibility(value: unknown) {
  if (isRepositoryVisibility(value)) {
    return null;
  }

  return "Choose public or private repository visibility.";
}

export function normalizeRepositoryDescription(
  value: unknown,
): string {
  if (isBlank(value)) {
    return DEFAULT_REPOSITORY_DESCRIPTION;
  }

  if (typeof value !== "string") {
    return DEFAULT_REPOSITORY_DESCRIPTION;
  }

  return value.trim();
}

export function validateRepositoryDescription(value: unknown) {
  if (isBlank(value)) {
    return null;
  }

  if (typeof value !== "string") {
    return "Repository description must be text.";
  }

  if (value.trim().length > REPOSITORY_DESCRIPTION_MAX_LENGTH) {
    return `Keep the repository description under ${REPOSITORY_DESCRIPTION_MAX_LENGTH} characters.`;
  }

  return null;
}

export function validateProjectBrief(value: unknown) {
  const content = getProjectBriefContent(value);

  if (isBlank(content)) {
    return null;
  }

  if (typeof content !== "string") {
    return "Project brief must be text.";
  }

  if (content.trim().length > PROJECT_BRIEF_MAX_LENGTH) {
    return `Keep the project brief under ${PROJECT_BRIEF_MAX_LENGTH} characters.`;
  }

  return null;
}

export function normalizeGenerationOptions(
  value: unknown,
): NormalizeGenerationOptionsResult {
  const errors: GenerationOptionsValidationError[] = [];
  const input = readGenerationOptionsInput(value);

  if (!input.ok) {
    errors.push(input.error);
  }

  const rawOptions = input.options;
  const rawVisibility =
    rawOptions.visibility ?? rawOptions.repositoryVisibility;
  const rawDescription =
    rawOptions.description ?? rawOptions.repositoryDescription;
  const visibility = normalizeRepositoryVisibility(rawVisibility);
  const visibilityError = isBlank(rawVisibility)
    ? null
    : validateRepositoryVisibility(rawVisibility);

  if (visibilityError) {
    errors.push({
      field: "visibility",
      message: visibilityError,
    });
  }

  const descriptionError = validateRepositoryDescription(rawDescription);

  if (descriptionError) {
    errors.push({
      field: "description",
      message: descriptionError,
    });
  }

  const projectBriefError = validateProjectBrief(rawOptions.projectBrief);

  if (projectBriefError) {
    errors.push({
      field: "projectBrief",
      message: projectBriefError,
    });
  }

  if (errors.length > 0) {
    return {
      ok: false,
      options: null,
      errors,
    };
  }

  return {
    ok: true,
    options: {
      visibility,
      description: normalizeRepositoryDescription(rawDescription),
      projectBrief: normalizeProjectBrief(rawOptions.projectBrief),
    },
    errors: [],
  };
}

function readGenerationOptionsInput(
  value: unknown,
):
  | { ok: true; options: GenerationOptionsInput }
  | {
      ok: false;
      options: GenerationOptionsInput;
      error: GenerationOptionsValidationError;
    } {
  if (value === undefined || value === null) {
    return {
      ok: true,
      options: {},
    };
  }

  if (!isRecord(value)) {
    return {
      ok: false,
      options: {},
      error: {
        field: "generationOptions",
        message: "Generation options must be an object.",
      },
    };
  }

  return {
    ok: true,
    options: {
      visibility: value.visibility,
      repositoryVisibility: value.repositoryVisibility,
      description: value.description,
      repositoryDescription: value.repositoryDescription,
      projectBrief: value.projectBrief,
    },
  };
}

function normalizeRepositoryVisibility(
  value: unknown,
): RepositoryVisibility {
  if (isBlank(value)) {
    return DEFAULT_REPOSITORY_VISIBILITY;
  }

  if (!isRepositoryVisibility(value)) {
    return DEFAULT_REPOSITORY_VISIBILITY;
  }

  return value.trim() === "private" ? "private" : "public";
}

function normalizeProjectBrief(value: unknown): ProjectBrief | null {
  const content = getProjectBriefContent(value);

  if (isBlank(content) || typeof content !== "string") {
    return null;
  }

  return {
    content: content.trim(),
  };
}

function getProjectBriefContent(value: unknown) {
  if (isRecord(value) && "content" in value) {
    return value.content;
  }

  return value;
}

function isRepositoryVisibility(
  value: unknown,
): value is RepositoryVisibility {
  return (
    typeof value === "string" &&
    (value.trim() === "public" || value.trim() === "private")
  );
}

function isBlank(value: unknown) {
  return (
    value === undefined ||
    value === null ||
    (typeof value === "string" && value.trim().length === 0)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
