import {
  finalizeProposalFiles,
  gitignoreTemplate,
  nextConfigTemplate,
  nextGlobalsTemplate,
  nextPackageJsonTemplate,
  nextTsconfigTemplate,
  postcssConfigTemplate,
  tailwindConfigTemplate,
} from "./common";
import type {
  GeneratedProposalFile,
  StackProposal,
  StackProposalDefinition,
} from "./types";

export const aiChatbotStarterDefinition = {
  id: "ai-chatbot-starter",
  name: "AI Chatbot Starter",
  description:
    "App Router, Tailwind, a chat page, an API route, and a provider-neutral AI adapter.",
  icon: "next",
} satisfies StackProposalDefinition;

export function buildAiChatbotStarterFiles(
  projectName: string,
): GeneratedProposalFile[] {
  return finalizeProposalFiles([
    {
      path: "README.md",
      content: readmeTemplate(projectName),
    },
    {
      path: ".env.example",
      content: envExampleTemplate(),
    },
    {
      path: ".gitignore",
      content: gitignoreTemplate(),
    },
    {
      path: "package.json",
      content: nextPackageJsonTemplate(projectName),
    },
    {
      path: "tsconfig.json",
      content: nextTsconfigTemplate(),
    },
    {
      path: "next.config.ts",
      content: nextConfigTemplate(),
    },
    {
      path: "postcss.config.mjs",
      content: postcssConfigTemplate(),
    },
    {
      path: "tailwind.config.ts",
      content: tailwindConfigTemplate(),
    },
    {
      path: "src/app/globals.css",
      content: nextGlobalsTemplate(),
    },
    {
      path: "src/app/layout.tsx",
      content: layoutTemplate(projectName),
    },
    {
      path: "src/app/page.tsx",
      content: homePageTemplate(projectName),
    },
    {
      path: "src/app/chat/page.tsx",
      content: chatPageTemplate(),
    },
    {
      path: "src/components/ChatPanel.tsx",
      content: chatPanelTemplate(),
    },
    {
      path: "src/app/api/chat/route.ts",
      content: chatRouteTemplate(),
    },
    {
      path: "src/lib/ai/provider.ts",
      content: aiProviderTemplate(),
    },
  ]);
}

export const aiChatbotStarterProposal = {
  definition: aiChatbotStarterDefinition,
  buildFiles: buildAiChatbotStarterFiles,
} satisfies StackProposal;

function readmeTemplate(projectName: string) {
  return `# ${projectName}

Next.js chatbot starter with a chat screen, an API route, and a small AI provider interface. It runs locally with a demo provider, so you can build the product flow before choosing a model vendor.

## Getting started

~~~bash
npm install
cp .env.example .env.local
npm run dev
~~~

Open http://localhost:3000/chat and send a message. The default provider returns a local demo response and does not call a paid service.

## Add a real AI provider

1. Install the SDK you want to use.
2. Add its environment variables to \`.env.local\`.
3. Replace \`demoAIProvider\` in \`src/lib/ai/provider.ts\` with a provider that implements \`AIProvider\`.
4. Keep provider-specific code inside \`src/lib/ai/provider.ts\` or a sibling module, then leave \`src/app/api/chat/route.ts\` focused on request validation and response shape.

The chat API expects an array of messages:

~~~json
{
  "messages": [
    { "role": "user", "content": "Draft a short welcome message." }
  ]
}
~~~

## Useful paths

- \`src/app/chat/page.tsx\` - chat route
- \`src/components/ChatPanel.tsx\` - client-side chat UI
- \`src/app/api/chat/route.ts\` - request validation and API response
- \`src/lib/ai/provider.ts\` - provider-neutral interface and demo provider
`;
}

function envExampleTemplate() {
  return `# The demo provider works without secrets.
AI_PROVIDER="demo"

# Add provider-specific values only after you wire a real provider.
# AI_API_KEY=""
`;
}

function layoutTemplate(projectName: string) {
  return `import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "${projectName}",
    template: "%s | ${projectName}",
  },
  description: "A provider-neutral chatbot starter generated by AgentStack.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function homePageTemplate(projectName: string) {
  return `import Link from "next/link";

export default function Home() {
  return (
    <main className="min-h-screen bg-zinc-50 px-6 py-12 text-zinc-950">
      <section className="mx-auto flex max-w-4xl flex-col gap-10">
        <nav className="flex items-center justify-between text-sm">
          <span className="font-semibold">${projectName}</span>
          <Link
            href="/chat"
            className="rounded-md border border-zinc-300 px-3 py-2 font-medium hover:bg-white"
          >
            Chat
          </Link>
        </nav>

        <div className="max-w-3xl py-16">
          <p className="text-sm font-medium uppercase tracking-[0.18em] text-zinc-500">
            Chatbot starter
          </p>
          <h1 className="mt-5 text-4xl font-semibold tracking-tight sm:text-6xl">
            A chat UI with the model vendor left open.
          </h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-600">
            Start with the conversation loop, request validation, and response
            contract. Add a real provider when the product behavior is clear.
          </p>
          <Link
            href="/chat"
            className="mt-8 inline-flex rounded-md bg-zinc-950 px-4 py-3 text-sm font-medium text-white hover:bg-zinc-800"
          >
            Open chat
          </Link>
        </div>
      </section>
    </main>
  );
}
`;
}

function chatPageTemplate() {
  return `import { ChatPanel } from "@/components/ChatPanel";

export const metadata = {
  title: "Chat",
};

export default function ChatPage() {
  return (
    <main className="min-h-screen bg-zinc-100 px-4 py-6 text-zinc-950 sm:px-6 lg:py-10">
      <section className="mx-auto flex max-w-4xl flex-col gap-5">
        <div>
          <p className="text-sm font-medium uppercase tracking-[0.18em] text-zinc-500">
            Chat
          </p>
          <h1 className="mt-2 text-3xl font-semibold tracking-tight">
            Test the conversation loop.
          </h1>
        </div>
        <ChatPanel />
      </section>
    </main>
  );
}
`;
}

function chatPanelTemplate() {
  return `"use client";

import { FormEvent, useMemo, useState } from "react";

type ChatRole = "user" | "assistant";

type ChatMessage = {
  id: string;
  role: ChatRole;
  content: string;
};

type ChatResponse = {
  message?: ChatMessage;
  error?: string;
};

const initialMessages: ChatMessage[] = [
  {
    id: "welcome",
    role: "assistant",
    content:
      "Ask a question and I will answer with the local demo provider until you wire a real model.",
  },
];

export function ChatPanel() {
  const [messages, setMessages] = useState<ChatMessage[]>(initialMessages);
  const [input, setInput] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [isSending, setIsSending] = useState(false);

  const canSend = useMemo(
    () => input.trim().length > 0 && !isSending,
    [input, isSending],
  );

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const content = input.trim();

    if (!content || isSending) {
      return;
    }

    const userMessage: ChatMessage = {
      id: crypto.randomUUID(),
      role: "user",
      content,
    };
    const nextMessages = [...messages, userMessage];

    setMessages(nextMessages);
    setInput("");
    setError(null);
    setIsSending(true);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          messages: nextMessages.map(({ role, content }) => ({ role, content })),
        }),
      });
      const data = (await response.json()) as ChatResponse;

      if (!response.ok || !data.message) {
        throw new Error(data.error ?? "The chat API did not return a reply.");
      }

      setMessages((currentMessages) => [...currentMessages, data.message]);
    } catch (caughtError) {
      setError(
        caughtError instanceof Error
          ? caughtError.message
          : "The chat request failed.",
      );
    } finally {
      setIsSending(false);
    }
  }

  return (
    <div className="flex min-h-[620px] flex-col overflow-hidden rounded-lg border border-zinc-200 bg-white shadow-sm">
      <div className="flex-1 space-y-4 overflow-y-auto p-4 sm:p-6">
        {messages.map((message) => (
          <div
            key={message.id}
            className={
              message.role === "user"
                ? "ml-auto max-w-[80%] rounded-lg bg-zinc-950 px-4 py-3 text-sm leading-6 text-white"
                : "mr-auto max-w-[80%] rounded-lg bg-zinc-100 px-4 py-3 text-sm leading-6 text-zinc-800"
            }
          >
            {message.content}
          </div>
        ))}
      </div>

      {error ? (
        <p className="border-t border-red-100 bg-red-50 px-4 py-3 text-sm text-red-700">
          {error}
        </p>
      ) : null}

      <form
        onSubmit={handleSubmit}
        className="flex flex-col gap-3 border-t border-zinc-200 p-4 sm:flex-row"
      >
        <label className="sr-only" htmlFor="message">
          Message
        </label>
        <textarea
          id="message"
          value={input}
          onChange={(event) => setInput(event.target.value)}
          placeholder="Ask about onboarding, support, or your product workflow..."
          rows={2}
          className="min-h-12 flex-1 resize-none rounded-md border border-zinc-300 px-3 py-3 text-sm outline-none ring-zinc-950/10 placeholder:text-zinc-400 focus:ring-4"
        />
        <button
          type="submit"
          disabled={!canSend}
          className="rounded-md bg-zinc-950 px-5 py-3 text-sm font-medium text-white hover:bg-zinc-800 disabled:cursor-not-allowed disabled:bg-zinc-300"
        >
          {isSending ? "Sending" : "Send"}
        </button>
      </form>
    </div>
  );
}
`;
}

function chatRouteTemplate() {
  return `import { NextResponse } from "next/server";

import { getAIProvider, type ChatMessage } from "@/lib/ai/provider";

export const runtime = "nodejs";

type ChatRequestBody = {
  messages?: unknown;
};

export async function POST(request: Request) {
  let requestBody: unknown;

  try {
    requestBody = await request.json();
  } catch {
    return NextResponse.json(
      { error: "Send a valid JSON request body." },
      { status: 400 },
    );
  }

  const body: ChatRequestBody = isChatRequestBody(requestBody)
    ? requestBody
    : {};
  const messages = parseMessages(body.messages);

  if (messages.length === 0) {
    return NextResponse.json(
      { error: "Send at least one chat message." },
      { status: 400 },
    );
  }

  const provider = getAIProvider();
  const reply = await provider.generateReply({ messages });

  return NextResponse.json({
    message: {
      id: crypto.randomUUID(),
      role: "assistant",
      content: reply.content,
    },
    provider: provider.id,
  });
}

function isChatRequestBody(value: unknown): value is ChatRequestBody {
  return typeof value === "object" && value !== null;
}

function parseMessages(value: unknown): ChatMessage[] {
  if (!Array.isArray(value)) {
    return [];
  }

  return value.filter(isChatMessage).map((message) => ({
    role: message.role,
    content: message.content.trim(),
  }));
}

function isChatMessage(value: unknown): value is ChatMessage {
  if (typeof value !== "object" || value === null) {
    return false;
  }

  const candidate = value as Record<string, unknown>;

  return (
    (candidate.role === "user" ||
      candidate.role === "assistant" ||
      candidate.role === "system") &&
    typeof candidate.content === "string" &&
    candidate.content.trim().length > 0
  );
}
`;
}

function aiProviderTemplate() {
  return `export type ChatMessage = {
  role: "system" | "user" | "assistant";
  content: string;
};

export type GenerateReplyInput = {
  messages: ChatMessage[];
};

export type GenerateReplyResult = {
  content: string;
};

export type AIProvider = {
  id: string;
  generateReply: (input: GenerateReplyInput) => Promise<GenerateReplyResult>;
};

const demoAIProvider: AIProvider = {
  id: "demo",
  async generateReply(input) {
    const lastUserMessage = [...input.messages]
      .reverse()
      .find((message) => message.role === "user");

    if (!lastUserMessage) {
      return {
        content: "Send a user message and I will reply from the demo provider.",
      };
    }

    return {
      content: \`Demo reply: I received "\${lastUserMessage.content}". Replace demoAIProvider with your model SDK when you are ready.\`,
    };
  },
};

export function getAIProvider(): AIProvider {
  return demoAIProvider;
}
`;
}
