import {
  finalizeProposalFiles,
  gitignoreTemplate,
  nextConfigTemplate,
  nextGlobalsTemplate,
  nextPackageJsonTemplate,
  nextTsconfigTemplate,
  postcssConfigTemplate,
  tailwindConfigTemplate,
} from "./common";
import type {
  GeneratedProposalFile,
  StackProposal,
  StackProposalDefinition,
} from "./types";

export const nextSaasStarterDefinition = {
  id: "next-saas-starter",
  name: "Next.js SaaS Starter",
  description:
    "App Router, Tailwind, Prisma, PostgreSQL, and a NextAuth-ready project shape.",
  icon: "next",
} satisfies StackProposalDefinition;

export function buildNextSaasStarterFiles(
  projectName: string,
): GeneratedProposalFile[] {
  return finalizeProposalFiles([
    {
      path: "README.md",
      content: readmeTemplate(projectName),
    },
    {
      path: ".env.example",
      content: envExampleTemplate(),
    },
    {
      path: ".gitignore",
      content: gitignoreTemplate(),
    },
    {
      path: "package.json",
      content: packageJsonTemplate(projectName),
    },
    {
      path: "tsconfig.json",
      content: nextTsconfigTemplate(),
    },
    {
      path: "next.config.ts",
      content: nextConfigTemplate(),
    },
    {
      path: "postcss.config.mjs",
      content: postcssConfigTemplate(),
    },
    {
      path: "tailwind.config.ts",
      content: tailwindConfigTemplate(),
    },
    {
      path: "src/app/globals.css",
      content: nextGlobalsTemplate(),
    },
    {
      path: "src/app/layout.tsx",
      content: layoutTemplate(projectName),
    },
    {
      path: "src/app/page.tsx",
      content: homePageTemplate(projectName),
    },
    {
      path: "src/app/dashboard/page.tsx",
      content: dashboardPageTemplate(),
    },
    {
      path: "src/app/api/auth/[...nextauth]/route.ts",
      content: authRouteTemplate(),
    },
    {
      path: "src/auth.ts",
      content: authTemplate(),
    },
    {
      path: "src/lib/prisma.ts",
      content: prismaClientTemplate(),
    },
    {
      path: "prisma/schema.prisma",
      content: prismaSchemaTemplate(),
    },
  ]);
}

export const nextSaasStarterProposal = {
  definition: nextSaasStarterDefinition,
  buildFiles: buildNextSaasStarterFiles,
} satisfies StackProposal;

function readmeTemplate(projectName: string) {
  return `# ${projectName}

Next.js SaaS starter with the App Router, Tailwind, Prisma, PostgreSQL, and a NextAuth-ready auth layer.

## Getting started

~~~bash
npm install
cp .env.example .env.local
npm run dev
~~~

Open http://localhost:3000 and visit \`/dashboard\` for the protected-area placeholder.

## Database

The app does not connect to the database on the home page, so it can run before Postgres is available. When you are ready to work on data models:

~~~bash
npm run db:generate
npm run db:push
~~~

The default \`DATABASE_URL\` in \`.env.example\` points at a local Postgres database. Replace it with your own local or hosted database URL before pushing schema changes.

## Auth

NextAuth is wired in \`src/auth.ts\` with no providers enabled yet. Add a provider, set its environment variables, then add an auth guard to the dashboard route.

## Useful paths

- \`src/app/page.tsx\` - public home page
- \`src/app/dashboard/page.tsx\` - signed-in app placeholder
- \`src/auth.ts\` - NextAuth config
- \`src/lib/prisma.ts\` - shared Prisma client
- \`prisma/schema.prisma\` - auth and workspace models
`;
}

function envExampleTemplate() {
  return `# Local Postgres example. Change the database name to match your project.
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/agentstack_saas?schema=public"

# Required by Auth.js in production. Generate with: npx auth secret
AUTH_SECRET=""
AUTH_URL="http://localhost:3000"

# Add provider values after you choose one.
# GITHUB_CLIENT_ID=""
# GITHUB_CLIENT_SECRET=""
`;
}

function packageJsonTemplate(projectName: string) {
  return nextPackageJsonTemplate(projectName, {
    dependencies: {
      "@auth/prisma-adapter": "^2.11.1",
      "@prisma/client": "^6.19.0",
      "next-auth": "^5.0.0-beta.31",
    },
    devDependencies: {
      prisma: "^6.19.0",
    },
    scripts: {
      "db:generate": "prisma generate",
      "db:push": "prisma db push",
      "db:studio": "prisma studio",
    },
  });
}

function layoutTemplate(projectName: string) {
  return `import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "${projectName}",
    template: "%s | ${projectName}",
  },
  description: "A focused SaaS starter generated by AgentStack.",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

function homePageTemplate(projectName: string) {
  return `import Link from "next/link";

const setupItems = [
  "Pick an auth provider in src/auth.ts.",
  "Point DATABASE_URL at your Postgres database.",
  "Shape the dashboard around one real user workflow.",
];

export default function Home() {
  return (
    <main className="min-h-screen bg-zinc-50 px-6 py-12 text-zinc-950">
      <section className="mx-auto flex max-w-5xl flex-col gap-10">
        <nav className="flex items-center justify-between text-sm">
          <span className="font-semibold">${projectName}</span>
          <Link
            href="/dashboard"
            className="rounded-md border border-zinc-300 px-3 py-2 font-medium hover:bg-white"
          >
            Dashboard
          </Link>
        </nav>

        <div className="grid gap-10 py-16 lg:grid-cols-[1.2fr_0.8fr] lg:items-center">
          <div className="space-y-6">
            <p className="text-sm font-medium uppercase tracking-[0.18em] text-zinc-500">
              SaaS starter
            </p>
            <h1 className="max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">
              Start with auth, data, and a real app route in place.
            </h1>
            <p className="max-w-2xl text-lg leading-8 text-zinc-600">
              This template gives you the App Router, Prisma, PostgreSQL, and
              the NextAuth files you need before the product work begins.
            </p>
            <Link
              href="/dashboard"
              className="inline-flex rounded-md bg-zinc-950 px-4 py-3 text-sm font-medium text-white hover:bg-zinc-800"
            >
              Open dashboard
            </Link>
          </div>

          <div className="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
            <h2 className="text-base font-semibold">First setup pass</h2>
            <ul className="mt-5 space-y-4 text-sm leading-6 text-zinc-600">
              {setupItems.map((item) => (
                <li key={item} className="flex gap-3">
                  <span className="mt-2 h-2 w-2 rounded-full bg-emerald-500" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </section>
    </main>
  );
}
`;
}

function dashboardPageTemplate() {
  return `const cards = [
  {
    label: "Workspace",
    value: "Acme Field Ops",
    detail: "Replace this with the signed-in user's active workspace.",
  },
  {
    label: "Plan",
    value: "Trial",
    detail: "Wire billing only after the first paid workflow is clear.",
  },
  {
    label: "Next step",
    value: "Add auth guard",
    detail: "Call auth() here after you add a provider in src/auth.ts.",
  },
];

export default function DashboardPage() {
  return (
    <main className="min-h-screen bg-zinc-100 px-6 py-10 text-zinc-950">
      <section className="mx-auto flex max-w-6xl flex-col gap-8">
        <div className="flex flex-col gap-3 border-b border-zinc-200 pb-6">
          <p className="text-sm font-medium uppercase tracking-[0.18em] text-zinc-500">
            Dashboard
          </p>
          <h1 className="text-3xl font-semibold tracking-tight">
            Build the first customer workflow here.
          </h1>
          <p className="max-w-2xl text-sm leading-6 text-zinc-600">
            The route is intentionally plain. Add navigation, data, and access
            control when the product shape is settled.
          </p>
        </div>

        <div className="grid gap-4 md:grid-cols-3">
          {cards.map((card) => (
            <article
              key={card.label}
              className="rounded-lg border border-zinc-200 bg-white p-5 shadow-sm"
            >
              <p className="text-sm text-zinc-500">{card.label}</p>
              <h2 className="mt-3 text-xl font-semibold">{card.value}</h2>
              <p className="mt-3 text-sm leading-6 text-zinc-600">
                {card.detail}
              </p>
            </article>
          ))}
        </div>
      </section>
    </main>
  );
}
`;
}

function authRouteTemplate() {
  return `import { handlers } from "@/auth";

export const { GET, POST } = handlers;
`;
}

function authTemplate() {
  return `import { PrismaAdapter } from "@auth/prisma-adapter";
import NextAuth from "next-auth";

import { prisma } from "@/lib/prisma";

export const { handlers, auth, signIn, signOut } = NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [],
});
`;
}

function prismaClientTemplate() {
  return `import { PrismaClient } from "@prisma/client";

const globalForPrisma = globalThis as unknown as {
  prisma?: PrismaClient;
};

export const prisma = globalForPrisma.prisma ?? new PrismaClient();

if (process.env.NODE_ENV !== "production") {
  globalForPrisma.prisma = prisma;
}
`;
}

function prismaSchemaTemplate() {
  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id            String                @id @default(cuid())
  name          String?
  email         String?               @unique
  emailVerified DateTime?
  image         String?
  accounts      Account[]
  sessions      Session[]
  memberships   WorkspaceMembership[]
  createdAt     DateTime              @default(now())
  updatedAt     DateTime              @updatedAt
}

model Account {
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?
  createdAt         DateTime @default(now())
  updatedAt         DateTime @updatedAt
  user              User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@id([provider, providerAccountId])
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  createdAt    DateTime @default(now())
  updatedAt    DateTime @updatedAt
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)
}

model VerificationToken {
  identifier String
  token      String
  expires    DateTime

  @@id([identifier, token])
}

model Workspace {
  id        String                @id @default(cuid())
  name      String
  slug      String                @unique
  members   WorkspaceMembership[]
  createdAt DateTime              @default(now())
  updatedAt DateTime              @updatedAt
}

model WorkspaceMembership {
  id          String        @id @default(cuid())
  workspaceId String
  userId      String
  role        WorkspaceRole @default(MEMBER)
  workspace   Workspace     @relation(fields: [workspaceId], references: [id], onDelete: Cascade)
  user        User          @relation(fields: [userId], references: [id], onDelete: Cascade)
  createdAt   DateTime      @default(now())
  updatedAt   DateTime      @updatedAt

  @@unique([workspaceId, userId])
}

enum WorkspaceRole {
  OWNER
  MEMBER
}
`;
}
