import assert from "node:assert/strict";
import test from "node:test";

import * as writerModule from "../../src/lib/github-bulk-writer";

test("validates safe generated file paths", () => {
  assert.equal(
    writerModule.validateGitHubBulkWriterPath("src/app/page.tsx"),
    "src/app/page.tsx",
  );
});

test("rejects unsafe generated file paths before GitHub requests", async () => {
  await assert.rejects(
    () =>
      writerModule.createRepositoryWithInitialCommit({
        githubToken: "ghp_test",
        repoName: "agentstack-test",
        description: "Generated by AgentStack.",
        private: false,
        files: [
          {
            path: "../package.json",
            content: "{}",
          },
        ],
      }),
    writerModule.GitHubValidationError,
  );
});

test("rejects duplicate generated file paths", async () => {
  await assert.rejects(
    () =>
      writerModule.createRepositoryWithInitialCommit({
        githubToken: "ghp_test",
        repoName: "agentstack-test",
        description: "Generated by AgentStack.",
        private: false,
        files: [
          {
            path: "README.md",
            content: "First",
          },
          {
            path: "README.md",
            content: "Second",
          },
        ],
      }),
    writerModule.GitHubValidationError,
  );
});

test("maps GitHub rate limits to a typed error", () => {
  const error = writerModule.toGitHubBulkWriterError({
    status: 403,
    message: "API rate limit exceeded",
    response: {
      headers: {
        "x-ratelimit-remaining": "0",
      },
    },
  });

  assert.ok(error instanceof writerModule.GitHubRateLimitError);
  assert.equal(error.code, "github_rate_limit");
  assert.equal(error.message, "GitHub rate limit reached. Try again later.");
});
